# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Don't complain on definitions like this. We like question marks!
# def some_boolean?; some_boolean; end
TrivialAccessors:
  ExactNameMatch: true

# Don't enforce any particular name for block params
SingleLineBlockParams:
  Enabled: false
