# use the shared YaST defaults
inherit_from:
  rubocop-1.59.0_yast_style.yml

# Don't enforce any particular name for block params
Style/SingleLineBlockParams:
  Enabled: false

# The general YaST agreement is 100 characters, so it fits into standard
# resolutions and Github's pull request view. But let's open the threshold a
# little bit
Layout/LineLength:
  Max: 105

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

# some storage API have size method, but without empty? method
# for details see https://github.com/yast/yast-storage-ng/pull/83
Style/ZeroLengthPredicate:
  Enabled: false

# the ".freeze" attribute for the constants is not nice
Style/MutableConstant:
  Enabled: false

# this is failing in storage wrapper, it will need more time to adapt
Style/FrozenStringLiteralComment:
  Enabled: false

# workaround https://github.com/rubocop-hq/rubocop/issues/6861
Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Naming/MethodParameterName:
  AllowedNames:
    - vg
    - md
    - lv
    - id
    - up
    - to
    - as

# Empty classes are used in tests to avoid build dependencies, so ignore them there
Lint/EmptyClass:
  Exclude:
    - test/**/*.rb
