# Copyright (c) [2019] SUSE LLC
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, contact SUSE LLC.
#
# To contact SUSE LLC about this file by physical or electronic mail, you may
# find current contact information at www.suse.com.

module Y2Partitioner
  module Widgets
    # Encrypted {Y2Storage::BlkDevice} type
    class EncryptType < CWM::ComboBox
      # Id for the events generated by this widget
      #
      # Useful for other widgets with handle_all_events
      alias_method :event_id, :widget_id

      def initialize(controller)
        textdomain "storage"

        @controller = controller
      end

      def init
        self.value = @controller.encrypt_type&.to_sym || :luks
      end

      # @macro seeAbstractWidget
      def store
        @controller.encrypt_type = value
      end

      def label
        _("Encryption type")
      end

      def items
        [
          [:plain, _("Random")],
          [:luks, _("LUKS")]
        ]
      end

      # @macro seeAbstractWidget
      def opt
        [:hstretch, :notify]
      end
    end
  end
end
